databases:
  - name: postgres
    ipAllowList: []
    databaseName: realtime_search_box
    user: realtime_search_box

services:
  - type: web
    name: realtime_search_box
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false